# Generated by Django 4.1.4 on 2022-12-22 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_rename_category_outcomecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 7, 14, 41, 456552, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
