# Generated by Django 4.1.4 on 2022-12-22 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_outcome_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 7, 16, 17, 267142, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 7, 16, 17, 316156, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
