# Generated by Django 4.1.4 on 2022-12-22 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_alter_income_pub_date_alter_outcome_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='pub_date',
            field=models.DateField(default=datetime.date(2022, 12, 22), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='pub_date',
            field=models.DateField(default=datetime.date(2022, 12, 22), verbose_name='date published'),
        ),
    ]
